### ISSUE TITLE
Document how to set time beg/end of an event

### ISSUE THREAD

**Issue by bzg** [codegouvfr/eleventy-plugin-calendar#2]

**Comment by hjonin** [comment]
There is actually no way to directly set the end time of an event - it works with a start date (variable `date`) and a variable `duration` (now described in the [documentation](https://github.com/codegouvfr/eleventy-plugin-calendar#usage)). Would it be a feature request?

**Comment by bzg** [comment]
Here is a more detailed proposal.

The user could either

- set the `start` and `end` variables in the frontmatter, and those variables would allow for HTML *date-time* formats.  When no time is given for `start` or `end`, fall back on `defaultStartTime` (e.g. `10:00` or `10:00:00` or `10:00:00-02:00`) and `defaultEndTime`;
- set the date and no duration for one-day events, and rely on `defaultStartTime` and `defaultEndTime`;
- set the date or a date-time and a duration in number of days; e.g. `date: 2023-10-16` and `duration: 4` would mean an event of 4 days, starting on Oct 16h, with a starting time of `defaultStartTime`, etc.  If a date-time is given, use the time as `defaultStartTime` and fall back on `defaultEndTime` for the end time of the last day.

WDYT?

**Comment by bzg** [comment]
After rethinking this, I propose we accept three cases:

- `date: 2023-10-16` for an all day event on Oct. 16th.
- `start: 2023-10-16` and `end: 2023-10-19` for a three days events.
- `start: 2023-10-16T10:00:00` and `end: 2023-10-16T12:00:00` for a 2h event on Oct. 16th.

In the .ics file this will translate respectively as:

- `DTSTART=;VALUE=DATE:20231016` and `DTEND=;VALUE=DATE:20231017` (`DTEND` is non-inclusive.)
- `DTSTART=;VALUE=DATE:20231016` and `DTEND=;VALUE=DATE:20231020`.
- `DTSTART:20231016T100000Z` and `DTEND:20231016T120000Z`.

A variation of the third case could be:

- `start: 2023-10-16T10:00:00` and `end: 2023-10-19T12:00:00` for an event start at 10am on Oct 16h and finishing at 12am on Oct 19th.

I suggest we simply forget about defaults, as users won't probably use them. WDY?

**Comment by hjonin** [comment]
It should be solved in the last version (`3.0.2`) and explained in the [documentation](https://github.com/codegouvfr/eleventy-plugin-calendar#notes-on-dates).

Defaults have indeed been removed for datetimes (but kept for organizer and location).

`duration` property has finally been kept to allow user use either `end` (preferred) or `duration`.
